
    /* eslint-disable */
    /* tslint:disable */
    // @ts-nocheck
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: jBiZ6mVcaqvvQhNgAZtxJj

    

    import * as React from "react"
    import {hasVariant, ensureGlobalVariants} from "@plasmicapp/react-web";
    import { CompLji7SnRgpYJ } from "./CompLji7SnRgpYJ";  // plasmic-import: LJI7SnRgpY-J/codeComponent
    

    export interface GlobalContextsProviderProps {
      children?: React.ReactElement;
      userSessionProps?: Partial<
           Omit<React.ComponentProps<typeof CompLji7SnRgpYJ>, "children">>;
    }

    export default function GlobalContextsProvider(props: GlobalContextsProviderProps) {
      
      const {
        children,
        userSessionProps
      } = props;

      
      return (
      <CompLji7SnRgpYJ
      {...userSessionProps}
      
      >
        { children }
      </CompLji7SnRgpYJ>
    )
    }
  